#------------------------------------------------------------------------------------------                                                                                      
#  ____           _____ _                        _ 
# |  _ \         / ____| |                      | |
# | |_) |_   _  | (___ | |__   __ _ ______ _  __| |
# |  _ <| | | |  \___ \| '_ \ / _` |_  / _` |/ _` |
# | |_) | |_| |  ____) | | | | (_| |/ / (_| | (_| |
# |____/ \__, | |_____/|_| |_|\__,_/___\__,_|\__,_|
#         __/ |                                    
#        |___/  
#------------------------------------------------------------------------------------------  
##Sprawdzanie 1.2##
#Komenda wykonywana przez konsole (nick) zastępuje nick gracza
ban: 'ban (nick) Przyznanie sie do wspomagaczy!'
#Nazwa narzędzia do sprawdzania
narzedzienazwa: 'Sprawdzanie'
#Id narzędzia do sprawdzania lub angielska nazwa
narzedzieid: 'blaze rod'
#Nazwa GUI Admina
gui: 'Menu Sprawdzania Admina'
#Zapisywanie EQ wiadomosc do sprawdzanego
zapisywanieeq: 'Trwa zapisywanie twojego eq zaczekaj chwile'
#Koniec sprawdzania gracz jest czysty
sprawdzaniekoniec: 'Jestes czysty sprawdzanie zakonczone!'
#Zwracanie eq wiadomość do gracza
zwracanieeq: 'Twoje eq jest teraz zwracane zaczekaj chwile..'
#TAG Sprawdzania w title
sprawdzanietag: '&cSPRAWDZANIE'
#EQ zwrócone
eqzwrocone: '&2Twoje eq zostalo zwrocone'
#EQ zapisane
eqzapisane: 'Twoje eq zostalo zapisane pomyslnie'
#Wiadomosc o braku permisji do komend (sprawdzania)
sprawdzpermmsg: '&cBrak permisji'
#Permisja ktora mozna przyznac do uzywania komend (sprawdzanie)
sprawdzallperm: 'perm.spr.all'
#NiePrzyznanie sie do wspomagaczy (nick) zastępuje nick gracz
nieprzyznanie: 'Gracz (nick) nie przyznal sie do cheatow musi byc sprawdzany'
#Brak gracza na serwerze wiadomość (nick) zastępuje nick gracza
noplayer: '&cGracz (nick) nie jest aktywny na serwerze.'
#Brak permisji do klikniecia tabliczki
sprpermmsg: 'Brak permisji do wykonania tej akcji, nie jestes teraz sprawdzany.'
#Permisja gracza sprawdzanego
jestemsprperm: 'jestem.spr.perm'
#Wiadomosc do sprawdzającego o zwrocie eq i zakonczeniu sprawdzania
eqzwroconemsg: 'Itemy gracza zostaly zwrocone a sprawdzanie zakoncozne.'
#  _  ______  _   _ _____ ______ _____    _____ ____  _   _ ______ _____ _____ _    _ 
# | |/ / __ \| \ | |_   _|  ____/ ____|  / ____/ __ \| \ | |  ____|_   _/ ____| |  | |
# | ' / |  | |  \| | | | | |__ | |      | |   | |  | |  \| | |__    | || |  __| |  | |
# |  <| |  | | . ` | | | |  __|| |      | |   | |  | | . ` |  __|   | || | |_ | |  | |
# | . \ |__| | |\  |_| |_| |___| |____  | |___| |__| | |\  | |     _| || |__| | |__| |
# |_|\_\____/|_| \_|_____|______\_____|  \_____\____/|_| \_|_|    |_____\_____|\____/   
